### ISSUE TITLE
Unable to run Cotopaxi commands

### ISSUE THREAD

**Issue by Seenujo** [Samsung/cotopaxi#2]
Hi ,
   I install Cotopaxi in kali. Whenever i run the command "sudo python -m cotopaxi.service_ping.py -h" i'm getting an error like "/usr/bin/python: No module named cotopaxi.service_ping.py" . Could you provide solution for this.
Kindly provide, step by step installation guide for Cotopaxi tool. This might helpful to perform test.

**Comment by badstranger** [comment]
it should be "sudo python -m cotopaxi.service_ping -h"

**Comment by Seenujo** [comment]
Yes, i tried the above command. Now, i'm getting error like "usr/bin/python: No module named cotopaxi"

**Comment by jakub-botwicz** [comment]
Cotopaxi was modified in order to use setuptools.
Please use updated installation guide.
