### ISSUE TITLE
Can not Receive UDP Responses

### ISSUE THREAD

**Issue by mateBANANE** [Samsung/cotopaxi#3]
Hello,

I have encountered a problem with Cotopaxi's CoAP functionality. In general, Cotopaxi does not receive any answers for UDP traffic. I have tested the modules service_ping, server_fingerprinter, and resource_listing against CoAP and, for verification, active_scanner against DTLS.

### Details
I have hosted a CoAP server from libcoap's examples and a DTLS server via `openssl s_server -dtls -cert server-cert.pem -key server-key.pem -accept 4444`. Furthermore, I run the service_ping module against the public coap.me:5683, as pinging is part of CoAP's regular functionality and not an attack.
I state each used command and its output in the following:

#### Service Ping

```
$ sudo python3 -m cotopaxi.service_ping --protocol CoAP coap.me 5683

[.] Started service ping
[+] Host 134.102.218.18:5683 does NOT respond to CoAP "protocol ping" message
[.] Finished service ping (for all addresses, ports and protocols)
================================================================================
Test statistics:
Messages sent: 2, responses received: 0, 100% message loss, test time: 2212 ms
================================================================================
Test results:
Active endpoints:
Total number of active endpoints: 0
Inactive endpoints: 1
```

#### Resource Listing 
I hosted a second machine on the network, its IP is 10.0.0.11

```
$ sudo python3 -m cotopaxi.resource_listing --protocol CoAP 10.0.0.11 5683 cotopaxi/lists/urls/coap_urls.txt 

[.] Started resource listing
[-] Url || is not available on server 10.0.0.11:5683 for method GET
[-] Url |.well-known| is not available on server 10.0.0.11:5683 for method GET
[-] Url |advanced| is not available on server 10.0.0.11:5683 for method GET
[-] Url |advancedSeparate| is not available on server 10.0.0.11:5683 for method GET
[-] Url |api| is not available on server 10.0.0.11:5683 for method GET
[-] Url |basic| is not available on server 10.0.0.11:5683 for method GET
[-] Url |big| is not available on server 10.0.0.11:5683 for method GET
[-] Url |block| is not available on server 10.0.0.11:5683 for method GET
.
.
.
================================================================================
Test statistics:
Messages sent: 23, responses received: 0, 100% message loss, test time: 16124 ms
================================================================================
Test results:
Active endpoints:
Total number of active endpoints: 0
Inactive endpoints: 21
```

#### Server Fingerprinter

I hosted a second machine on the network, its IP is 10.0.0.11

```
$ sudo python3.6 -m cotopaxi.server_fingerprinter --protocol CoAP 10.0.0.11 5683

[.] Started service fingerprinting
Begin emission:
Finished sending 1 packets.
..
Received 2 packets, got 0 answers, remaining 1 packets
Begin emission:
Finished sending 1 packets.
..
Received 2 packets, got 0 answers, remaining 1 packets
[.] Host 10.0.0.11:5683 is dead before test!
[.] CoAP fingerprinting stopped for 10.0.0.11:5683 because server is not responding
    (use --ignore-ping-check if you want to continue anyway)!
[.] Finished service fingerprinting (for all addresses, ports and protocols)
================================================================================
Test statistics:
Messages sent: 2, responses received: 0, 100% message loss, test time: 12275 ms
================================================================================
Test results:
Identified:
Total number of identified: 0
Inactive endpoints: 1
```
#### Active Scanner

I hosted my OpenSSL DTLS server on 10.0.0.11:4444
```
$sudo python3.6 -m cotopaxi.active_scanner 10.0.0.11 4444        

[.] Started active security scanning
Begin emission:
Finished sending 1 packets.
..
Received 2 packets, got 0 answers, remaining 1 packets
Begin emission:
Finished sending 1 packets.
.
Received 1 packets, got 0 answers, remaining 1 packets
Begin emission:
Finished sending 1 packets.
.
Received 1 packets, got 0 answers, remaining 1 packets
[+] Server 10.0.0.11:4444 is not responding before starting scan - skipping this host!
    (use --ignore-ping-check if you want to continue anyway)
[.] Finished active security scanning (for all addresses, ports and protocols)
================================================================================
Test statistics:
Messages sent: 3, responses received: 0, 100% message loss, test time: 20665 ms
================================================================================
Test results:
Identified issues:
Total number of identified issues: 0
Inactive endpoints: 0
```

### Investigation and Solution Attempts
First of all, I have tried to inspect the problem in Wireshark. The site coap.me, my self-hosted libcoap-server, and OpenSSL did always respond to Cotopaxi's requests.

Then, I started to debug the code. I have noticed that in common_utils.py:220 Scapy's sr1 function is called, but does never return a response. I am in the know that Cotopaxi's network errors are mostly subject to Scapy.

But when I created a separate script and send exactly the same packet as Cotopaxi via sr1, it returned a response. This was also the case when I installed Cotopaxi and all its dependencies in a fresh pip venv and run my script there.

I tested it for Python 2.7, 3.6, 3.7, and 3.8 on two machines, one with the latest Kali Linux and one with the latest Manjaro.

### Request
Have you encountered this issue already? Is there any way in which Cotopaxi changes something on how Scapy handles responses? Am I missing something else? Thank you in advance.  Nevertheless, it looks like a great and promising tool which I would really like to use.

**Comment by jakub-botwicz** [comment]
Hi @mateBANANE!

What versions of scapy and scapy-ssl_tls versions are installed on your system?

**Comment by jakub-botwicz** [comment]
Hi @mateBANANE!

I have reproduced this problem and made a fix (https://github.com/Samsung/cotopaxi/commit/fa906218bf8433b6d46185c05d0eb0b570634ec4).
There is a problem with the scapy sr1 function, that I cannot diagnose in detail - I suspect that this may be problem with scapy and operating system (e.g. some setting was changed in the system) or with scapy-ssl_tls and scapy (unfortunately scapy-ssl_tls is not maintained anymore and changes in scapy cause interoperability issues).
My fix switches from sr1 to standard Python UDP send and receive for non-spoofed payloads and for sr1 / sniff for spoofed packets.

Please confirm whether this fix works for you and if not - we will reopen the issue and investigate.

**Comment by mateBANANE** [comment]
Hi,

the issue is resolved on my side. Thank you very much!

I am using the scap-ssl_tls version referenced in your setup guide. The current commit is https://github.com/kalidasya/scapy-ssl_tls/commit/c5c51f1695ef8c95a3a0dc446f0765df5f2a5293. 

Scapy is installed in version 2.4.3.
