### ISSUE TITLE
Move away from hexdump

### ISSUE THREAD

**Issue by fabaff** [Samsung/cotopaxi#7]
`hexdump` has not be maintained for at least 5 years. The upstream repository is no longer available and the source at PyPI is missing at least the license file.

Please consider to migrate to a different module than `hexdump` as this is a blocker to include `cotopaxi` into distributions at least those where `hexdump` is not already present.

Thanks

**Comment by jakub-botwicz** [comment]
Fixed with 0ed28cbee0a4c3a3d3d717e3290fdb5b51b68e00

Thank you for reporting @fabaff !
